
server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://MySQL-8.2:3306/bank?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  liquibase:
    change-log: db/migration/db.changelog-1.yaml
    enabled: true

jwt:
  secret: f7bf5efa77d9ed25ffc9c3bff6f6d532
  expirationMinutes: 60

#Что нужно сделать:
#  - Указать настройки подключения к базе данных.
#  - Указать порт приложения.
#  - Настроить параметры безопасности и JWT.
#  - Включить Swagger UI.
